### ISSUE TITLE
[bug] mana output hatch don't work

### ISSUE THREAD

**Issue by Biviho** [Frinn38/Modular-Magic#17]
adding a machine and a recipe that make mana create a machine that consume the input and produce 0 mana.
The machine is correct, the recipe is recognized, the machine run without any problem, but the mana output hatch don' contain any mana.
Checking with ct nbt reveal that the output hatch stay at 0 mana while the machine run.

my recipe for example take 1 essentia from praecantatio, auram, mythus and vitium, 1 energy per tick for 100 tick and should produce 1 mana

**Comment by Biviho** [comment]
looks like it's not working only if using json, with crafttweaker it works, but it could also be that there is something wrong with my json as mana is not documented and is easyer to find the the syntax in the code for crafttweaker than for json

**Comment by Frinn38** [comment]
Botania support is basically a copy-paste of the Modular Diversity one that someone had PR [here](https://github.com/Frinn38/Modular-Magic/pull/9) so it should work the same. If you still need help with MM recipe jsons you can try the Astral Sorcery discord (it has a MM section since it's the same dev).
